### ISSUE TITLE
No ranging result from both phones

### ISSUE THREAD

**Issue by BillyYiuCimda** [CrazyChaoz/Minimal_Working_UWB_App#3]
I tried this code on Pixel 7 Pro and Galaxy S24 Plus. One set to Controller and one to Controlee and entered address and preamble index as required. After I clicked COMMUNICATE button, no distance showed up. I tried to update the uwb:1.0.0-alpha07 to uwb:1.0.0-alpha08 but the program quits after the connection, this behavior is the same as the official uwbRanging demo program from Android Developer. I guess it is something to do the difference between Pixel and Galaxy. For Pixel, Distance, Azimuth and Elevation are all true but for Galaxy, only Distance is true, the other two are false. Can you take a look to see what is the real root cause?

**Comment by CrazyChaoz** [comment]
Interesting, I tested it on Pixel 6 Pro, Pixel 7 Pro and a Galaxy Note 20(?) Pro, and they all seemed to work rather well, although P6P has no elevation angles.

Did you try the latest push? 
I fixed some api change/regression related bug.

**Comment by CrazyChaoz** [comment]
The Exception would be interesting.

If its some "session key is needed" then this is fixed, if its "library not up do date with backend" then some rebuild would do the trick.

There is also a good probability the phones need to be restarted at times, since the connection cleanup isnt always 100% working.

**Comment by BillyYiuCimda** [comment]
After upgrade and restart, it can work now. Interestingly, now it can work with uwb:1.0.0-alpha08 but the official uwbRanging program still doesn't work. However, the program is not very stable, it hangs and needs restart quite frequently.

**Comment by CrazyChaoz** [comment]
> official uwbRanging program still doesn't work. 

You could try to put a `byte[]{0,0,0,0,0,0,0,0}` as sessionKey, instead of null, if you get an error related to that, otherwise just hit me up with the exception, I probably also faced it before 🙃

> However, the program is not very stable, it hangs and needs restart quite frequently.

I know it isn't the most stable, and the Kotlin impl is probably better, but it is meant as a _somewhat_ working demo, in the sense of _hey, how good does this uwb thing in phones work_ . I could probably look at the cleanup of the coroutine stuff, but as a techdemo it does its thing _well enough_ I think.

Also it is alpha software. 
It really feels like alpha software.

You are lucky your phones don't get a kernel panic anymore from starting an uwbsession. I had to enrol a phone to the Android 14 beta since the UWB chip at some point died and not even resets were helping.

**Comment by BillyYiuCimda** [comment]
I couldn't find sessionKey in the uwbRanging source code, I only see sessionKeyInfo but it is random, not null. Even I use zero array, it still quit after getting connection, while running the channelFlow. I know Alpha08 is still not perfect, but I wonder why your latest code can solve my quiting problem with Alpha08. I know it is not fair for you to troubleshoot the code from somebody else. Anyway, thanks for your help.

Oriiginal code:
val sessionKeyInfo = Random.nextBytes(8)

**Comment by BillyYiuCimda** [comment]
I have opened an issue to Android, not sure whether it will be taken care of. https://github.com/android/connectivity-samples/issues/308#issue-2415745384

**Comment by BillyYiuCimda** [comment]
Since uwb:1.0.0-alpha06, RangingParameters was updated but the UwbRanging example code is still expecting old parameter set, that is why it has error. Your code makes it work for uwb:1.0.0-alpha08, thanks.
https://github.com/android/connectivity-samples/issues/308#issuecomment-2237993717

**Comment by CrazyChaoz** [comment]
❤️
